repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        stages: [commit]
        language: system
        entry: poetry run isort --force-grid-wrap 2
        types: [python]

      - id: black
        name: black
        stages: [commit]
        language: system
        entry: poetry run black --line-length=72
        types: [python]

      - id: autoflake
        name: autoflake
        stages: [commit]
        language: system
        entry: poetry run autoflake --in-place --remove-unused-variables --remove-all-unused-imports --recursive .

      - id: flake8
        name: flake8
        stages: [commit]
        language: system
        entry: poetry run flake8
        types: [python]
        exclude: setup.py

      - id: mypy
        name: mypy
        stages: [commit]
        language: system
        entry: poetry run mypy personalization
        types: [python]
        pass_filenames: false

  -  repo: https://github.com/pre-commit/pre-commit-hooks
     rev: v4.2.0
     hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
