name: CI

on:
  push:
    paths:
      - 'personalization/**'
  pull_request:
    paths:
      - 'personalization/**'

env:
  PYTHON_VERSION: ${{ secrets.PYTHON_VERSION }}
  POETRY_VERSION: ${{ secrets.POETRY_VERSION }}

jobs:
  install-deps-and-test:
    name: Install Poetry and Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org/ | POETRY_VERSION=${{ env.POETRY_VERSION }} python
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies and main package
        run: |
          poetry install --no-root
          poetry install
          poetry run pre-commit run --all-files --color always || true
          poetry run coverage run --omit 'tests/*' -m pytest
          poetry run coverage report -m > coverage.txt
          total_coverage=$(tail -n 1 coverage.txt  | awk '{print $NF}' | sed 's/%//')
          echo "Coverage is $total_coverage%"
      - name: Publish to PyPI
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        env:
          TWINE_USERNAME: ${{ env.PYPI_USER_NAME }}
          TWINE_PASSWORD: ${{ env.PYPI_USER_PASSWORD }}
          TWINE_NON_INTERACTIVE: 0
        run: |
          rm -rf dist
          poetry build -f wheel
          poetry run twine upload --skip-existing dist/*