name: CI

on:
  push:
    branches:
      - 'ci/**'
      - 'main'
  pull_request:
    branches:
      - 'ci/**'
      - 'main'

env:
  PYTHON_VERSION: ${{ secrets.PYTHON_VERSION }}
  POETRY_VERSION: ${{ secrets.POETRY_VERSION }}

jobs:
  install-deps-and-test:
    name: Install Poetry and Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org/ | POETRY_VERSION=${{ env.POETRY_VERSION }} python
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies and main package
        run: |
          poetry install --no-root
          poetry install
          poetry run pre-commit run --show-diff-on-failure --color=always
          poetry run coverage run --omit 'tests/*' -m pytest
          poetry run coverage report -m > coverage.txt
          total_coverage=$(tail -n 1 coverage.txt  | awk '{print $NF}' | sed 's/%//')
          echo "Coverage is $total_coverage%"

  publish:
    name: Publish to PyPI
    needs: install-deps-and-test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push' && needs.install-deps-and-test.result == 'success'
    env:
      TWINE_USERNAME: ${{ secrets.PYPI_USER_NAME }}
      TWINE_PASSWORD: ${{ secrets.PYPI_USER_PASSWORD }}
      TWINE_NON_INTERACTIVE: 0
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org/ | POETRY_VERSION=${{ env.POETRY_VERSION }} python
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          poetry install --no-root

      - name: Publish to PyPI
        run: |
          rm -rf dist
          poetry build -f wheel
          poetry run twine upload --skip-existing dist/*

      - name: Publish coverage to Codecov
        uses: codecov/codecov-action@v1.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
  build-docker-image:
    name: Build Docker image
    needs: install-deps-and-test
    if: (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/ci/**') && github.event_name == 'push' && needs.install-deps-and-test.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: username/personalization:latest
